### ISSUE TITLE
Does not build on aarch64

### ISSUE THREAD

**Issue by dustin** [nikita-volkov/ptr-poker#3]
text.c fails to compile.  It looks like it's target-specific implementations.

**Comment by nikita-volkov** [comment]
What about the version 0.1.1.3? We've had SSE2 instructions added in 0.1.1.4 (see https://github.com/nikita-volkov/ptr-poker/pull/1). It might be the reason.

Pinging @ethercrow.

**Comment by ethercrow** [comment]
Hello together.

The optimizations should be conditional on `__x86_64__` being defined. Could you post the compilation error?

**Comment by nikita-volkov** [comment]
@dustin Can you try compiling the version 0.1.1.3? Also please provide the error details
